apiVersion: v1
kind: Service
metadata:
  labels:
    service: zookeeper
  name: zookeeper
spec:
  ports:
  - name: "2181"
    port: 2181
    targetPort: 2181
    nodePort: 30010
  selector:
    service: zookeeper
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: zookeeper
  name: zookeeper
spec:
  replicas: 2
  selector:
    matchLabels:
      service: zookeeper
  template:
    metadata:
      labels:
        service: zookeeper
    spec:
      containers:
      - image: bitnami/zookeeper:latest
        name: zookeeper
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        - name: "auth.enabled"
          value: "false"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "256m"
      restartPolicy: Always